name: CI
on:
  push:
    branches: ["develop"]

jobs:
  build:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Dockerhub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

  deployment: 
    needs: build
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy to VPS
        # with:
        #   host: ${{ secrets.SERVER }}
        #   username: ${{ secrets.SERVER_USERNAME }}
        #   key: ${{ secrets.SSH_PRIVATE_KEY }}
        #   port: ${{ secrets.SERVER_PORT }}
        #   script: |
        #     whoami
        #     docker stop user-service || true && docker rm user-service || true
        #     docker pull ${{  vars.IMAGE_NAME  }}
        #     docker run -d 8081:8081 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SERVER }}
          USER_NAME : ${{ secrets.SERVER_USERNAME  }}
        
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            whoami
            docker stop ${{ vars.CONTAINER_NAME }} || true && docker image rm -f tangguhriyadi/${{ vars.IMAGE_NAME }} || true
            docker pull tangguhriyadi/${{  vars.IMAGE_NAME  }}
            docker run -d -p 8081:8081 --name ${{ vars.CONTAINER_NAME }} tangguhriyadi/${{ vars.IMAGE_NAME }}
          '

